jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/643982099481/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'triviacomidacolombiana@appspot.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v1'