name: Deploy Option Valuation App

on:
  push:
    branches:
      - master

jobs:
  deploy_google_app:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        working-directory: OptionValuationWeb
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/643982099481/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'github-service@triviacomidacolombiana.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v1'